sudo: required
dist: trusty
language: php

cache:
  bundler: true
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"
php:
  - 7.0

addons:
  apt:
    packages:
    # Dependencies for Chrome.
    - libappindicator1
    - fonts-liberation

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

  # Initialize xvfb (see https://docs.travis-ci.com/user/gui-and-headless-browsers)
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

  # Download Chrome Driver
  - LATEST_CHROMEDRIVER=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
  - wget http://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - mkdir -p $HOME/.composer/vendor/bin
  - mv -f chromedriver $HOME/.composer/vendor/bin/
  - rm chromedriver_linux64.zip

  # Update Chrome.
  - export CHROME_BIN=/usr/bin/google-chrome
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome-stable_current_amd64.deb
  - rm google-chrome-stable_current_amd64.deb
  - google-chrome --version

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/bin:$PATH"

  # Create the MySQL database and add a user for testing.
  - mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'lightning'@'localhost' IDENTIFIED BY 'lightning'; GRANT ALL ON drupal.* TO 'lightning'@'localhost';"

  # PHP conf tweaks
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Build the Lightning code base.
  - composer install

  # Install Lightning.
  - cd $TRAVIS_BUILD_DIR/docroot
  - ../bin/drush site-install lightning --yes --account-pass=admin --db-url=mysql://lightning:lightning@127.0.0.1/drupal

  # Update to version of Lightning with sub-profile support.
  - cd $TRAVIS_BUILD_DIR
  - composer require acquia/lightning:dev-8.x-subprofile --no-update
  # We need to blow away the lock file and core entirely because of a bug in
  # composer-patches. See:
  - rm composer.lock
  - rm -rf docroot/core
  - composer install

  # Convert existing extend file to proper sub-profile.
  - cd $TRAVIS_BUILD_DIR
  - ./bin/lightning-subprofile $TRAVIS_BUILD_DIR/docroot/sites/default/lightning.extend.yml

  # Install Lightning sub-profile.
  - cd $TRAVIS_BUILD_DIR/docroot
  - ../bin/drush site-install lightning_extend --yes --account-pass=admin --db-url=mysql://lightning:lightning@127.0.0.1/drupal
  - ../bin/drush config-set system.logging error_level all --yes

before_script:
  - ../bin/drush runserver --default-server=builtin 8080 &>/dev/null &

  # Start Selenium and dump its ginormous log into a temporary file.
  - jdk_switcher use oraclejdk8
  - mkdir tmp
  - selenium-server-standalone -port 4444 -log tmp/selenium2.log &
  - sleep 5
  - cd ..

  # Prepare Behat configuration.
  - composer run prepare-behat

script:
  - bin/behat --strict --stop-on-failure --tags=~layout

matrix:
  fast_finish: true
